import styles from './legal.module.css';

export default function Legal() {
  return (
    <div className={styles.legalPage}>
      <div className={styles.legalContent}>
        <h1>Legal Information</h1>
        
        <section id="privacy">
          <h2>Privacy Policy</h2>
          <p>Last updated: January 14, 2025</p>

          <h3>Information We Collect</h3>
          <p>When you use Inkling, we collect:</p>
          <ul>
            <li>Email address (for account management and communication)</li>
            <li>Usage data to improve our Chrome extension</li>
            <li>YouTube video URLs that you request summaries for</li>
          </ul>

          <h3>How We Use Your Information</h3>
          <p>We use your information to:</p>
          <ul>
            <li>Provide YouTube video summaries</li>
            <li>Manage your subscription</li>
            <li>Send important service updates</li>
            <li>Improve our summarization technology</li>
          </ul>

          <h3>Data Security</h3>
          <p>We implement industry-standard security measures to protect your data. We do not store video content, only the summaries you generate.</p>

          <h3>Third-Party Services</h3>
          <p>We use trusted third-party services for:</p>
          <ul>
            <li>Payment processing</li>
            <li>Email communication</li>
            <li>Analytics (to improve our service)</li>
          </ul>
        </section>

        <section id="terms">
          <h2>Terms of Service</h2>
          <p>Last updated: January 14, 2025</p>

          <h3>Acceptable Use</h3>
          <p>By using Inkling, you agree to:</p>
          <ul>
            <li>Use the Chrome extension for lawful purposes only</li>
            <li>Not attempt to reverse engineer the extension</li>
            <li>Maintain the security of your account</li>
            <li>Comply with YouTube's terms of service</li>
          </ul>

          <h3>Content and Summaries</h3>
          <p>Summaries generated by Inkling are for personal use only. We do not claim ownership of YouTube content or generated summaries.</p>

          <h3>Service Availability</h3>
          <p>While we strive for consistent service, we cannot guarantee uninterrupted access to Inkling. We reserve the right to modify or discontinue features with reasonable notice.</p>

          <h3>Account Termination</h3>
          <p>We may suspend or terminate accounts that violate these terms or engage in abusive behavior.</p>
        </section>

        <section id="refund">
          <h2>Subscription and Cancellation Policy</h2>
          <p>Last updated: January 14, 2025</p>

          <h3>Subscription Terms</h3>
          <p>Inkling is a subscription-based service with monthly billing. By subscribing, you agree to recurring monthly charges until you cancel your subscription.</p>

          <h3>Cancellation Policy</h3>
          <ul>
            <li>You may cancel your subscription at any time</li>
            <li>Cancellations will be processed within one business day</li>
            <li>Your subscription will remain active until the end of your current billing cycle</li>
            <li>No partial refunds are provided for unused portions of the billing cycle</li>
          </ul>

          <h3>No Refund Policy</h3>
          <p>We do not offer refunds for any subscription payments. All sales are final.</p>

          <h3>How to Cancel</h3>
          <p>To cancel your subscription, please contact our support team at cameron@forge.co. Include your account email in your request.</p>
        </section>

        <p className={styles.contactInfo}>
          For questions about these policies, please contact me at <a href="mailto:cameron@forge.co">cameron@forge.co</a>
        </p>
      </div>
    </div>
  );
} 